sonar.projectKey=Fanantenana-ds_smartrh-api
sonar.organization=fanantenana-ds
sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.js
sonar.verbose=false
sonar.scanner.skipJreProvisioning=true