sonar.projectKey=https://sonarcloud.io/project/overview?id=Fanantenana-ds_smartrh-api
sonar.organization=https://sonarcloud.io/organizations/fanantenana-ds/projects
sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info